In [1]:
import  os
import  warnings
warnings.filterwarnings("ignore")

In [2]:
import   pandas                as     pd
import   numpy                 as     np
import   matplotlib.pyplot     as     plt
import   seaborn               as     sns
import   scipy.stats           as     stats
from     scipy                 import stats

In [3]:
from   statsmodels.stats.outliers_influence   import   variance_inflation_factor

In [4]:
def calculate_vif_(X, thresh = 5):
    cols = X.columns
    variables = np.arange(X.shape[1])
    dropped=True
    while dropped:
        dropped=False
        c = X[cols[variables]].values
        vif = [variance_inflation_factor(c, ix) for ix in np.arange(c.shape[1])]

        maxloc = vif.index(max(vif))
        if max(vif) > thresh:
            print('dropping \'' + X[cols[variables]].columns[maxloc] + '\' at index: ' + str(maxloc))
            variables = np.delete(variables, maxloc)
            dropped=True

    print('Remaining variables:')
    print(X.columns[variables])
    ncdf = X[cols[variables]]
    return ncdf

In [5]:
num_file  = r'E:\DSE-FT-B-JUN24-G2\Data\DSEFTB-JUN24-G2-Models_2024_11_24_12_14_44.csv'
num_df    =  pd.read_csv(num_file, encoding = 'Latin-1')
num_df.columns

Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'Target'],
      dtype='object')

In [6]:
num_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 45 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      101766 non-null  int64
 1   gender                    101766 non-null  int64
 2   age                       101766 non-null  int64
 3   admission_type_id         101766 non-null  int64
 4   discharge_disposition_id  101766 non-null  int64
 5   admission_source_id       101766 non-null  int64
 6   time_in_hospital          101766 non-null  int64
 7   payer_code                101766 non-null  int64
 8   medical_specialty         101766 non-null  int64
 9   num_lab_procedures        101766 non-null  int64
 10  num_procedures            101766 non-null  int64
 11  num_medications           101766 non-null  int64
 12  number_outpatient         101766 non-null  int64
 13  number_emergency          101766 non-null  int64
 14  number_inpatient          101766 non-null  int64
 15  diag_1                    101766 non-null  int64
 16  diag_2                    101766 non-null  int64
 17  diag_3                    101766 non-null  int64
 18  number_diagnoses          101766 non-null  int64
 19  max_glu_serum             101766 non-null  int64
 20  A1Cresult                 101766 non-null  int64
 21  metformin                 101766 non-null  int64
 22  repaglinide               101766 non-null  int64
 23  nateglinide               101766 non-null  int64
 24  chlorpropamide            101766 non-null  int64
 25  glimepiride               101766 non-null  int64
 26  acetohexamide             101766 non-null  int64
 27  glipizide                 101766 non-null  int64
 28  glyburide                 101766 non-null  int64
 29  tolbutamide               101766 non-null  int64
 30  pioglitazone              101766 non-null  int64
 31  rosiglitazone             101766 non-null  int64
 32  acarbose                  101766 non-null  int64
 33  miglitol                  101766 non-null  int64
 34  troglitazone              101766 non-null  int64
 35  tolazamide                101766 non-null  int64
 36  insulin                   101766 non-null  int64
 37  glyburide-metformin       101766 non-null  int64
 38  glipizide-metformin       101766 non-null  int64
 39  glimepiride-pioglitazone  101766 non-null  int64
 40  metformin-rosiglitazone   101766 non-null  int64
 41  metformin-pioglitazone    101766 non-null  int64
 42  change                    101766 non-null  int64
 43  diabetesMed               101766 non-null  int64
 44  Target                    101766 non-null  int64
dtypes: int64(45)
memory usage: 34.9 MB

## 5) Assumptions 
-	Check for the assumptions to be satisfied for each of the models in 

*	Regression – SLR, Multiple Linear Regression, Logistic Regression
*	Classification – Decision Tree, Random Forest, SVM, Bagged and boosted models
*	Clustering – PCA (multi-collinearity), K-Means (presence of outliers, scaling, conversion to numerical etc.)

### Check for assumptions of the Classification models such Decision Tree, Random Forest, SVM, Bagged and boosted models

ust as with most things in life, assumptions can directly lead to success or failure. Similarly in machine learning, appreciating the assumed logic behind machine learning techniques will guide you toward applying the best tool for the data.

Ref: https://www.kdnuggets.com/2021/02/machine-learning-assumptions.html

* The assumption of "Absence of multi-collinearity" affects the Logistic Regression model.
* In Decision Tree model, the tree can choose any of the collinear features to create splits and hence the two features divide the share of importance. So absence of multi-collinearity is important to get good results.
* In Random Forest model, there is no assumption of formal distribution. Being a non-parametric model, it can handle skewed and multi-model data.

### Check for multi-collinearity

In [12]:
num_df.columns

Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'Target'],
      dtype='object')

In [13]:
Y  = num_df['Target']

In [14]:
X  = num_df[['race', 'gender', 'age', 'admission_type_id','discharge_disposition_id', 'admission_source_id', 'time_in_hospital','payer_code',\
              'medical_specialty', 'num_lab_procedures','num_procedures', 'num_medications', 'number_outpatient','number_emergency','number_inpatient',\
              'diag_1', 'diag_2', 'diag_3','number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin','repaglinide', 'nateglinide', 'chlorpropamide',\
              'glimepiride','acetohexamide', 'glipizide', 'glyburide', 'tolbutamide','pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol',\
              'troglitazone','tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin','glimepiride-pioglitazone', 'metformin-rosiglitazone',\
              'metformin-pioglitazone', 'change', 'diabetesMed']]

In [15]:
#Checking for multicolleniarty in our independant variables
# VIF dataframe
vif_data            =  pd.DataFrame()
vif_data["feature"] =  X.columns
  
# calculating VIF for each feature
vif_data["VIF"]     = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]

vif_data

                     feature          VIF
0                       race     5.028275
1                     gender     1.900535
2                        age    18.008124
3          admission_type_id     3.466394
4   discharge_disposition_id     1.580362
5        admission_source_id     3.484454
6           time_in_hospital     4.510338
7                 payer_code     7.904918
8          medical_specialty     4.349158
9         num_lab_procedures     7.140737
10            num_procedures     2.038671
11           num_medications     8.440431
12         number_outpatient     1.128063
13          number_emergency     1.147483
14          number_inpatient     1.403763
15                    diag_1     5.556627
16                    diag_2     4.427613
17                    diag_3     3.654026
18          number_diagnoses    20.315630
19             max_glu_serum    42.560188
20                 A1Cresult    14.752328
21                 metformin     9.767257
22               repaglinide    57.939694
23               nateglinide   131.493807
24            chlorpropamide   747.601292
25               glimepiride    20.762682
26             acetohexamide     1.000271
27                 glipizide    11.324946
28                 glyburide    12.160638
29               tolbutamide     1.001038
30              pioglitazone    17.536553
31             rosiglitazone    19.597909
32                  acarbose   284.610180
33                  miglitol  1045.029015
34              troglitazone     1.000412
35                tolazamide     1.001306
36                   insulin     4.163413
37       glyburide-metformin   139.137071
38       glipizide-metformin     1.001648
39  glimepiride-pioglitazone     1.000245
40   metformin-rosiglitazone     1.000363
41    metformin-pioglitazone     1.000409
42                    change     3.377373
43               diabetesMed     6.667470

In [16]:
vif_data.loc[vif_data['VIF'] > 5]

                feature          VIF
0                  race     5.028275
2                   age    18.008124
7            payer_code     7.904918
9    num_lab_procedures     7.140737
11      num_medications     8.440431
15               diag_1     5.556627
18     number_diagnoses    20.315630
19        max_glu_serum    42.560188
20            A1Cresult    14.752328
21            metformin     9.767257
22          repaglinide    57.939694
23          nateglinide   131.493807
24       chlorpropamide   747.601292
25          glimepiride    20.762682
27            glipizide    11.324946
28            glyburide    12.160638
30         pioglitazone    17.536553
31        rosiglitazone    19.597909
32             acarbose   284.610180
33             miglitol  1045.029015
37  glyburide-metformin   139.137071
43          diabetesMed     6.667470

In [17]:
vif_data.loc[vif_data['VIF'] > 5, 'feature'].to_list()

['race',
 'age',
 'payer_code',
 'num_lab_procedures',
 'num_medications',
 'diag_1',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'glipizide',
 'glyburide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'glyburide-metformin',
 'diabetesMed']

### Observations

### Interpretation of VIF value

The higher the value, the greater the correlation of the variable with other variables. Values of more than 4 or 5 are sometimes regarded as being moderate to high, with values of 10 or more being regarded as very high.

The following **22** variables have VIF value above the threshold value of 5:
1) 'race',
2) 'age',
3) 'payer_code',
4) 'num_lab_procedures',
5) 'num_medications',
6) 'diag_1',
7) 'number_diagnoses',
8) 'max_glu_serum',
9) 'A1Cresult',
10) 'metformin',
11) 'repaglinide',
12) 'nateglinide',
13) 'chlorpropamide',
14) 'glimepiride',
15) 'glipizide',
16) 'glyburide',
17) 'pioglitazone',
18) 'rosiglitazone',
19) 'acarbose',
20) 'miglitol',
21) 'glyburide-metformin',
22) 'diabetesMed'
    
We need to remove variables having greater than the threshold value of 5 from our dataset.

In [19]:
calculate_vif_(X)

dropping 'miglitol' at index: 33
dropping 'chlorpropamide' at index: 24
dropping 'acarbose' at index: 31
dropping 'glyburide-metformin' at index: 34
dropping 'nateglinide' at index: 23
dropping 'repaglinide' at index: 22
dropping 'max_glu_serum' at index: 19
dropping 'number_diagnoses' at index: 18
dropping 'glimepiride' at index: 20
dropping 'rosiglitazone' at index: 25
dropping 'age' at index: 2
dropping 'pioglitazone' at index: 23
dropping 'A1Cresult' at index: 17
dropping 'glyburide' at index: 20
dropping 'glipizide' at index: 19
dropping 'num_medications' at index: 10
dropping 'metformin' at index: 16
dropping 'payer_code' at index: 6
dropping 'num_lab_procedures' at index: 7
dropping 'diabetesMed' at index: 24
Remaining variables:
Index(['race', 'gender', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'time_in_hospital', 'medical_specialty',
       'num_procedures', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'acetohexamide',
       'tolbutamide', 'troglitazone', 'tolazamide', 'insulin',
       'glipizide-metformin', 'glimepiride-pioglitazone',
       'metformin-rosiglitazone', 'metformin-pioglitazone', 'change'],
      dtype='object')

,race,gender,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_procedures,number_outpatient,number_emergency,...,acetohexamide,tolbutamide,troglitazone,tolazamide,insulin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change
0,2,0,6,25,1,1,37,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,2,0,1,1,7,3,15,0,0,0,...,0,0,0,0,3,0,0,0,0,0
2,0,0,1,1,7,2,24,5,2,0,...,0,0,0,0,1,0,0,0,0,1
3,2,1,1,1,7,2,18,1,0,0,...,0,0,0,0,3,0,0,0,0,0
4,2,1,1,1,7,1,15,0,0,0,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,0,1,1,3,7,3,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101762,0,0,1,4,5,5,18,3,0,0,...,0,0,0,0,2,0,0,0,0,1
101763,2,1,1,1,7,1,10,0,1,0,...,0,0,0,0,0,0,0,0,0,0
101764,2,0,2,3,7,10,62,2,0,0,...,0,0,0,0,3,0,0,0,0,0
101765,2,1,1,1,7,6,18,3,0,0,...,0,0,0,0,1,0,0,0,0,1

In [20]:
non_collinear_vars     = ['race', 'gender', 'admission_type_id', 'discharge_disposition_id','admission_source_id', 'time_in_hospital',\
                        'medical_specialty','num_procedures', 'number_outpatient', 'number_emergency','number_inpatient', 'diag_1', 'diag_2', 'diag_3',\
                        'acetohexamide','tolbutamide', 'troglitazone', 'tolazamide', 'insulin','glipizide-metformin', 'glimepiride-pioglitazone',\
                        'metformin-rosiglitazone', 'metformin-pioglitazone', 'change']
X_                     =  num_df[non_collinear_vars]
#Checking for multicolleniarty in our independant variables
# VIF dataframe
vif_data1              =  pd.DataFrame()
vif_data1["feature"]   =  X_.columns  
# calculating VIF for each feature
vif_data1["VIF"]        =  [variance_inflation_factor(X_.values, i) for i in range(len(X_.columns))]

vif_data1

                     feature       VIF
0                       race  4.359777
1                     gender  1.838964
2          admission_type_id  3.265068
3   discharge_disposition_id  1.550978
4        admission_source_id  3.050408
5           time_in_hospital  3.341036
6          medical_specialty  3.632561
7             num_procedures  1.761066
8          number_outpatient  1.115361
9           number_emergency  1.136362
10          number_inpatient  1.371299
11                    diag_1  4.735922
12                    diag_2  4.019477
13                    diag_3  3.385220
14             acetohexamide  1.000243
15               tolbutamide  1.000480
16              troglitazone  1.000274
17                tolazamide  1.000659
18                   insulin  3.369900
19       glipizide-metformin  1.000461
20  glimepiride-pioglitazone  1.000128
21   metformin-rosiglitazone  1.000107
22    metformin-pioglitazone  1.000133
23                    change  2.072833

### Observations

We observe that all the 24 variables are non-collinear and their **VIF value less than the threshold value of 5**.
With this data, the important assumption of absence of multi-collinearity is satisfied.